// app/routes/index.tsx
export default function Index() {
  return (
    <div>
      <h1>Hi,</h1>
      <p>
        My name is Jonas, and I work as a Software Developer in Gothenburg,
        Sweden.
      </p>
      <p>
        Welcome to my playground where I think out loud while learning, and
        tinker with things I find interesting.
      </p>
    </div>
  );
}

// src/routes/+page.svelte
<section>
  <h1>Hi,</h1>
  <p>My name is Jonas, and I work as a Software Developer in Gothenburg, Sweden.</p>
  <p>
    Welcome to my playground where I think out loud while learning, and tinker with things I find
    interesting.
  </p>
</section>

<style>
  section {
    padding: 0 20px 20px 20px;
  }

  h1 {
    margin: unset;
  }
</style>
